<div class="text-center">
    <table class="mx-auto">
        <tr>
            <th></th>
            <th>1<br>8:00-8:45</th>
            <th>2<br>8:55-9:40</th>
            <th>3<br>9:50-10:35</th>
            <th>4<br>10:45-11:30</th>
            <th>5<br>11:40-12:25</th>
            <th>6<br>12:35-13:20</th>
            <th>7<br>13:30-14:15</th>
            <th>8<br>14:25-15:10</th>
            <th>9<br>15:20-16:05</th>
        </tr>
        <tr>
            <th>Pondělí</th>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
        <tr>
            <th>Úterý</th>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
        </tr>
        <tr>
            <th>Středa</th>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
        </tr>
        <tr>
            <th>Čtvrtek</th>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
        </tr>
        <tr>
            <th>Pátek</th>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
            <td>PVA<br>Matav5<br>S329</td>
        </tr>
    </table>
</div>

